modLoader="javafml" #mandatory
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Vazkii/Botania/issues" #optional
displayURL="https://botaniamod.net" #optional
logoFile="logo.png" #optional
credits="Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw" #optional
authors="Vazkii, wiiv, williewillus, dylan4ever" #optional

[[mods]]
modId="botania"
version="${file.jarVersion}"
displayName="Botania"
description='''
Botania is a mod that adds nature magic to Minecraft'''

[[dependencies.botania]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botania]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-36,)"
    side="BOTH"

[[dependencies.botania]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.1-3.0,)"
    ordering="AFTER"
    side="BOTH"
